### ISSUE TITLE
[tracking] Connect to BQ with SQL alchemy

### ISSUE THREAD

**Issue by claramoreirag** [TensorOpsAI/LLMstudio#179]
- [ ]  Explore: https://github.com/googleapis/python-bigquery-sqlalchemy
- [ ] Build mockup project connecting and understanding BQ + SQL alchemy
- [ ] Understand changes needed to current code
- [ ] Make changes
